name: CI
on:
  pull_request:
    branches:
      - develop

jobs:
  build_android:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_API_URL: ${{ secrets.API_URL }}
      - name: Update build version
        shell: bash
        run: 'sed -i "s/version: 0.0.1+1/version: 0.0.1+$GITHUB_RUN_NUMBER/1" pubspec.yaml'
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk
      - name: App Center Distribute
        uses: devussy/AppCenter-Distribute-Github-Action@v1.0.2
        with:
          app: DevMagic/freeflow-app
          token: ${{ secrets.APP_CENTER_TOKEN }}
          group: Collaborators
          file: build/app/outputs/flutter-apk/app-release.apk
          silent: true